### ISSUE TITLE
apollo-errors

### ISSUE THREAD

**Issue by ecwyne** [gramps-graphql/gramps-errors#1]
It's probably worth taking a look at https://github.com/thebigredgeek/apollo-errors and https://github.com/thebigredgeek/apollo-resolvers to see if it makes sense to use them  directly or to learn from their patterns and mistakes.

**Comment by jlengstorf** [comment]
I looked at those originally, and they appear to be tackling different use cases. Specifically: this package is intended to create errors that can be linked from a limited client-side error message to a comprehensive server log via a UUID. That may be possible with `apollo-errors`, but we'd still be wrapping the library with our own code.

I _do_ think there's probably some value in refactoring to remove the intermediate dependency on `graphql-apollo-errors`, because it doesn't do much that we can't handle ourselves with (probably) less code. However, I don't think there's any urgency here; there are plenty of things that GrAMPS needs well in advance of worrying about this helper lib.
